### ISSUE TITLE
can't see any build tools (composer, drush, console) in a new image/container?

### ISSUE THREAD

**Issue by laurencefass** [docker-library/drupal#115]
i've docker pull'd drupal (8.5) image for the first time and exec'd into a shell to to do manual (drush si) installation. neither drush nor composer are present in the image. there is a composer.json file but im left wondering how does it install without composer? 

do i install drush, composer and drupal cli myself in this image if i want to use them? 

as module installation is dependent on initial install method, should i use composer or drush to extend my drupal docker site?

if this image doesn't contain developer tools is there an image better suited for developers and command line installation?

thanks

**Comment by johnny12150** [comment]
I got the same issue.

**Comment by laurencefass** [comment]
any reply on this please? what is the scope of use for this image? dev? prod?

as this is the official image, an early reply would be much appreciated.

thanks

**Comment by tianon** [comment]
> ... as this is the official image ...

See the fine print on https://github.com/docker-library/drupal#readme -- "official images" is the name of the program run by Docker Inc under which this image resides, which is _not_ to say that it is official according to the Drupal project (quite the opposite, in fact).

The scope of this image is to have a working installation of Drupal, which is why it does not contain any development tools such as `drush`, `composer`, etc.

If there is an explicit recommendation from Drupal upstream that we should install those tools in most standard Drupal installations (not just during development), then we'd be happy to look at including them, but otherwise we try to stick very closely to upstream's official recommendations for deployment.

**Comment by laurencefass** [comment]
many thanks for clarification.
