### ISSUE TITLE
How to add mysqld start in this Dockerfile?

### ISSUE THREAD

**Issue by for0231** [docker-library/drupal#123]
https://github.com/docker-library/drupal/blob/3e9c13c3b59dfe2a896898a601dc0e4d975c18a9/8.5/fpm-alpine/Dockerfile#L54

I want to use this docker file to build one environment for drupal, it will include mysql and preinstall Drupal 8;

But I have no idea for start mysql and so on, Would you add these content for next time?

**Comment by mstenta** [comment]
It's actually recommended ("best practice") to have MySQL in a separate container. The Drupal container is really an Apache/Nginx container with Drupal included. Docker containers are best thought of as a "single running process".

You can use Docker Compose to easily spin up a Drupal container and a MySQL container at the same time - and link them together so that Drupal can access the db.

There is an example docker-compose.yml file on the Drupal image's page on Docker Hub that shows how to do that: https://hub.docker.com/_/drupal/

**Comment by for0231** [comment]
There is a trouble with this solution, Every time I want to use these environmental, it must install every time, but I want to pre install Drupal enviornment when I start my docker container, it can't be convenient for this. how to start mysqld in Dockerfile ?
I still want to pre install Drupal in Dockerfile like this,

`RUN /usr/bin/mysqld --user=root --console && \
  vendor/bin/drush si -y --account-pass=admin --db-url=mysql://root:root@localhost/drupal`
This command is error, any idea for this?

**Comment by wglambert** [comment]
There's a lot of questions you have about using the image, I'm not fully understanding what they all are; you would get better responses over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since the repository issues aren't necessarily for usability questions on docker or the images
