### ISSUE TITLE
SQLSTATE 42000 Syntax Error 1231 Variable 'sql_mode' can't be set to value 'NO_AUTO_CREATE_USER' in drupal 8 container

### ISSUE THREAD

**Issue by themanfrommsu** [docker-library/drupal#131]
downloaded newest drupal image with the command:
docker pull drupal

Set up container (linking to existing MySQL container):
docker run --name mydrupal --link mysql80:mysql -p 8080:80 -d drupal

Received following error when connected to docker container via web browser and at point where typing in dbusername/dbpassword/dbname:
SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'

Was able to fix the problem by performing the following edits in the drupal container:
1. core/lib/Drupal/Core/Database/Driver/mysql/Connection.php (183): Remove NO_AUTO_CREATE_USER
2. core/lib/Drupal/Core/Database/Schema.php (202): change "table_name" to "TABLE_NAME as table_name"

Found the fix at the following website:
https://www.drupal.org/project/drupal/issues/2966523

**Comment by yosifkit** [comment]
Correct, the bug you linked is not fixed until drupal `8.6` and the current `latest` docker image is only `8.5.7`.  I think you could just switch to MySQL 5.7 rather than MySQL 8 or wait for the updated Drupal `8.6` images.  It does look like they released `8.6` yesterday, so I'll try to get in a PR to update the Dockerfile.
