### ISSUE TITLE
8.6 image not working

### ISSUE THREAD

**Issue by ruiengana** [docker-library/drupal#145]
Hi, latest image is not working. Run fails because with it cant load Apache MPM module.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue, I don't see any issues with the startup

```console
$ docker pull drupal:8.6
8.6: Pulling from library/drupal
f7e2b70d04ae: Pull complete 
744aedb7995c: Pull complete 
07afe22f8a58: Pull complete 
c7bf4f31c4a4: Pull complete 
b528e75732cc: Pull complete 
27e7d214ded2: Pull complete 
894549c23c16: Pull complete 
852bf3883bf8: Pull complete 
c8e5e0b946ad: Pull complete 
7f4f81e11b94: Pull complete 
4cd5dd8dc11e: Pull complete 
8575717bb21a: Pull complete 
7c1343f569e1: Pull complete 
087fe341a6a1: Pull complete 
c7038cea657b: Pull complete 
02cd6d0d5ef9: Pull complete 
Digest: sha256:f58d48741871a234a188bab95bd22bda23c03d54d2f050d7dcabf80f4aed4802
Status: Downloaded newer image for drupal:8.6

$ docker run -it --rm drupal:8.6
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 05 01:19:00.443000 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.15 configured -- resuming normal operations
[Tue Mar 05 01:19:00.455027 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by ruiengana** [comment]
When I run same commands I get this.

$ docker pull drupal:8.6
Trying to pull repository registry.access.redhat.com/drupal ...
Trying to pull repository docker.io/library/drupal ...
8.6: Pulling from docker.io/library/drupal
f7e2b70d04ae: Pull complete
744aedb7995c: Pull complete
07afe22f8a58: Pull complete
c7bf4f31c4a4: Pull complete
b528e75732cc: Pull complete
27e7d214ded2: Pull complete
894549c23c16: Pull complete
852bf3883bf8: Pull complete
c8e5e0b946ad: Pull complete
7f4f81e11b94: Pull complete
4cd5dd8dc11e: Pull complete
8575717bb21a: Pull complete
7c1343f569e1: Pull complete
087fe341a6a1: Pull complete
c7038cea657b: Pull complete
02cd6d0d5ef9: Pull complete
Digest:
sha256:c30aaaa25e735015418691d643c492d99f7dce86ff96e43b7ea20bf36764fe80
Status: Downloaded newer image for docker.io/drupal:8.6
$ docker run -it --rm drupal:8.6
AH00534: apache2: Configuration error: No MPM loaded.
$

**Comment by wglambert** [comment]
Looks like an incompatibility with your filesystem/storage drivers in your environment https://github.com/docker-library/php/issues/392#issuecomment-337484590

**Comment by brotherhui** [comment]
> Looks like an incompatibility with your filesystem/storage drivers in your environment [docker-library/php#392 (comment)](https://github.com/docker-library/php/issues/392#issuecomment-337484590)

Followed by this link, the docker cannot be restarted. 
[root@sevenos drupal8.6.10]# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-03-07 14:44:07 EST; 5s ago
     Docs: http://docs.docker.com
  Process: 7931 ExecStart=/usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --seccomp-profile=/etc/docker/seccomp.json $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $ADD_REGISTRY $BLOCK_REGISTRY $INSECURE_REGISTRY $REGISTRIES (code=exited, status=1/FAILURE)
 Main PID: 7931 (code=exited, status=1/FAILURE)

Mar 07 14:44:07 sevenos.akira.local systemd[1]: Starting Docker Application Container Engine...
Mar 07 14:44:07 sevenos.akira.local dockerd-current[7931]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both ...icemapper)
Mar 07 14:44:07 sevenos.akira.local systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 07 14:44:07 sevenos.akira.local systemd[1]: Failed to start Docker Application Container Engine.
Mar 07 14:44:07 sevenos.akira.local systemd[1]: Unit docker.service entered failed state.
Mar 07 14:44:07 sevenos.akira.local systemd[1]: docker.service failed.

**Comment by tianon** [comment]
These sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) (the issues are not a support forum).
