### ISSUE TITLE
New Drupal 8.5.14 and 8.6.13 security releases

### ISSUE THREAD

**Issue by codycraven** [docker-library/drupal#147]
https://www.drupal.org/SA-CORE-2019-004 was released today. The automation hasn't yet built the new images.

I'm not sure what the best way to notify for these high priority releases (see #144). Let me know if there's a better way than opening an issue.

**Comment by wglambert** [comment]
Looks like the updates were committed shortly after this issue was made
https://github.com/docker-library/drupal/commit/6cd1dd522ad508295a24c2f66fb41079b1dcc3af
https://github.com/docker-library/drupal/commit/ad7ae4e7d42746c98e55fd489e1ed5f510ba1f23

And the PR to the official images
https://github.com/docker-library/official-images/pull/5579

**Comment by tianon** [comment]
Which is merged now, so should be built and available soon.
