### ISSUE TITLE
SECURITY: CVE-2019-0197 security issue

### ISSUE THREAD

**Issue by nobso** [docker-library/drupal#148]
We have been using Drupal image from https://github.com/docker-library/drupal/blob/master/8.6/apache/Dockerfile#L2 which internally pulls the following apache

```
Server version: Apache/2.4.25 (Debian)
Server built:   2018-11-03T18:46:19
```
The Apache 2.4.x < 2.4.39 is detected with Multiple Vulnerabilities,

   

- A privilege escalation vulnerability exists in module scripts due to an ability to execute arbitrary code as the parent process by manipulating the scoreboard. (CVE-2019-0211)
-    An access control bypass vulnerability exists in mod_auth_digest due to a race condition when running in a threaded server. An attacker with valid credentials could authenticate using another username. (CVE-2019-0217)
-    An access control bypass vulnerability exists in mod_ssl when using per-location client certificate verification with TLSv1.3. (CVE-2019-0215)

In addition, Apache httpd is also affected by several additional vulnerabilities including a denial of service, read-after-free and URL path normalization inconsistencies.

More details: [httpd/CHANGES_2.4.39](apache.mirrors.hoobly.com//httpd/CHANGES_2.4.39)

Can we upgrade the apache version as soon as possible?

**Comment by yosifkit** [comment]
For CVE's in general we normally update about every 30 days ([faq entry](https://github.com/docker-library/faq/tree/1e39dbd29ffe96dc9cd10a9393a526e90ee049bc#why-does-my-security-scanner-show-that-an-image-has-cves))
> We also rebuild earlier if there is a critical security need

--------------------
Now to respond to these specific ones:

For CVE-2019-0211 see https://github.com/docker-library/php/issues/810

CVE-2019-0215, CVE-2019-0197: in Debian stretch and jessie 
> apache2 \<not-affected> (Vulnerable code introduced later)
>
> \- https://security-tracker.debian.org/tracker/CVE-2019-0215
> \- https://security-tracker.debian.org/tracker/CVE-2019-0197

CVE-2019-0217: ~@tianon, Is this serious enough to warrant an early Debian rebuild or hackery in the php Dockerfiles?~ ([security.debian](https://security-tracker.debian.org/tracker/CVE-2019-0217))  This CVE does not apply to the `php:apache` docker images. It is "when running in a threaded server" and we only configure php to run on `mpm_prefork` which is "a non-threaded, pre-forking web server".

------

Since only one CVE applies, I'll close this one and keep the tracking in docker-library/php#810
