### ISSUE TITLE
FPM based images are broken

### ISSUE THREAD

**Issue by DavidHernandez** [docker-library/drupal#159]
Hi,

I've been trying to use the drupal:fpm-alpine docker image with no luck. I was not sure if the documentation was wrong or the problem was the image itself.

I tried the apache based image and it works correctly. Then, I tried the FPM image (no alpine) and it has the same error.

This issue is very easy to replicate, just use the sample command provided by the README, but using any FPM based image:

`docker run --name some-drupal -p 8080:80 -d drupal:fpm-alpine`

Then, access to `localhost:8080` or `127.0.0.1:8080` and you will see the next error:
![Screenshot from 2019-11-13 16-04-21](https://user-images.githubusercontent.com/877002/68775739-4ccdb280-062f-11ea-9247-8afb63b34f57.png)

I tried a little bit of debugging and I found the next: the `FPM` image is by default configured to use the port `9000`, not the port `80`. You can see it using `docker ps`:
![Screenshot from 2019-11-13 16-06-28](https://user-images.githubusercontent.com/877002/68775963-98805c00-062f-11ea-8afd-b586093377f3.png)

After fixing this and starting again the container using this time the right port, this is still not working:
`docker run --name some-drupal -p 8080:9000 -d drupal:fpm-alpine`

I have no idea where to check, I have no previous experience working with FPM. I do not know if the error is in the Drupal FPM Dockerfile or in the FPM Dockerfile itself.

I am willing to invest some time to solve the issue, but I do not know from where to start. Any pointers?

Regards,
David.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/php#phpversion-fpm

This variant contains PHP-FPM, which is a FastCGI implementation for PHP. See [the PHP-FPM website](https://php-fpm.org/) for more information about PHP-FPM.

In order to use this image variant, some kind of reverse proxy (such as NGINX, Apache, or other tool which speaks the FastCGI protocol) will be required.

Some potentially helpful resources:

-	[PHP-FPM.org](https://php-fpm.org/)
-	[simplified example by @md5](https://gist.github.com/md5/d9206eacb5a0ff5d6be0)
-	[very detailed article by Pascal Landau](https://www.pascallandau.com/blog/php-php-fpm-and-nginx-on-docker-in-windows-10/)
-	[Stack Overflow discussion](https://stackoverflow.com/q/29905953/433558)
-	[Apache httpd Wiki example](https://wiki.apache.org/httpd/PHPFPMWordpress)

**Comment by Hexdump74** [comment]
Could you please just add a word on https://hub.docker.com/_/drupal about the need for a reverse-proxy to use the fpm image ? I wrongly assumed that nginx was included, just as apache is included in the 'standard' image. Even a single word in the doc would have saved me time and efforts.
Thanks

**Comment by tianon** [comment]
@Hexdump74 good point -- we have some notes in PHP's description: https://github.com/docker-library/docs/tree/88d2a5127d19e429b0e539cbb213fa3885317ee8/php#phpversion-fpm

I've opened https://github.com/docker-library/docs/pull/1765 to put those notes on `drupal` and `wordpress` too.
