### ISSUE TITLE
It does not work with apline fpm php

### ISSUE THREAD

**Issue by nehakotlaTR** [docker-library/drupal#180]
When I run the alpine php fpm tagged image. Drupal does not start

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by nehakotlaTR** [comment]
Hi,

So I downloaded this image from drupal -with version docker pull drupal:8-fpm-alpine3.12 and trying to run command - docker run --name drupalalpine8 -p 8080:80 drupal:8-fpm-alpine3.12 and its giving me below error and cant connect to drupal with this image. Also the latest drupal image is using Debian-buster-slim image it as lot of vulnerabilities.

Error –

curl localhost:8080
curl: (56) Recv failure: Connection reset by peer



[cid:image003.jpg@01D67D28.4DB88330]

Thanks,
Neha

**Comment by wglambert** [comment]
The FPM variant doesn't come with a web server by default
https://github.com/docker-library/docs/tree/master/drupal#drupalversion-fpm
>This variant contains PHP-FPM, which is a FastCGI implementation for PHP. See the PHP-FPM website for more information about PHP-FPM.
In order to use this image variant, some kind of reverse proxy (such as NGINX, Apache, or other tool which speaks the FastCGI protocol) will be required.

Also for vulnerabilities see https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
And https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.

A CVE doesn't imply having an actual vulnerability, and often is even a false positive (given how most distributions handle versioning/security updates in stable releases). If there are actionable items we can resolve, we're happy to do so (and do so actively). We update all Debian based images to include any updates in apt packages at least monthly (we regenerate the base images and then rebuild all dependent images).
