### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by mtucker502** [docker-library/drupal#182]
What is the best or preferred method for accessing this Docker container from a subdirectory?

I am using Traefik and want to be able to access Drupal at http://example.com/drupal.

**Comment by wglambert** [comment]
You'd want to specify `doc_root` in php https://www.php.net/manual/en/security.cgi-bin.doc-root.php
And then for Traefik you could use this article as a reference point https://medium.com/@iced_burn/reverse-proxy-in-traefik-with-subdirectories-eef4261939e

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
