### ISSUE TITLE
cookies for features?

### ISSUE THREAD

**Issue by funkyfuture** [docker-library/drupal#2]
ciao,

i'm one of two maintainers of [that Drupal-image](https://github.com/samos123/docker-drupal). that image aims to provide an easily extendable vanilla Drupal-experience as well as a base for also easily customized Drupal-images. notably, it features:
- environment-based configuration of
  - database-settings
  - PHP's `UPLOAD`\- & `MEMORY_LIMIT`
- an `entrypoint.sh` that provides hooks for an inital setup (default if no db is detected) and pre-launch
- convenient `drush`-usage in scripts and bash
- Drupal's recommended PHP-settings and -extensions
- default-settings, so a vanilla-instance passes [security-review](https://www.drupal.org/project/security_review)

if you think that any of these features fits to this image, we offer to upstream it. feel free to review the repository in question. depending on your response we'd prepare commits then.

by that opportunity, are there plans to publish guidelines what functionality an image from this library sould or must not provide?

**Comment by yosifkit** [comment]
I'm not that familiar with drupal, but I am sure some of these features would be useful to users.  As far as what official images should and should not provide, I think the current big line is not adding anything provider specific, like auto-config for running in Azure, Google, or Amazon.  Docker based autoconfig for finding a database is fine (ala links and env vars).  We try to keep as close to upstream as possible and limit most passed config.  If configuration is easier through a file, it is better to document that rather than having countless environment variables.

@tianon, are there any specific features that @funkyfuture could contribute from his image?
