### ISSUE TITLE
Remove opcache.fast_shutdown from PHP settings section

### ISSUE THREAD

**Issue by jnoordsij** [docker-library/drupal#236]
When checking the Dockerfile in this repo to see if it had relevant ideas or settings I could use for a Dockerfile of my own, I noticed the `opcache.fast_shutdown` being used. After looking it up however, I found out this directive has been removed since PHP 7.2.0 (see https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.fast-shutdown). So it may as well be removed from the settings here.

**Comment by yosifkit** [comment]
Oh neat. Yeah seems reasonable to drop it from the Dockerfiles:

https://github.com/docker-library/drupal/blob/31babf9557e7073927d12e8c80b834a9a3aba7e3/Dockerfile.template#L78-L86

I guess upstream should update their documentation as well (https://www.php.net/manual/en/opcache.installation.php), since that is where it came from.

**Comment by jnoordsij** [comment]
Yeah I thought about that, but I think the policy on their docs is currently to document everything back to version 7.0.0, so they might not want to do that yet. I'll raise an issue over there just in case.
