### ISSUE TITLE
[security] Vulnerable version of postgresql in drupal:10.3.6-php8.3-fpm-alpine3.20

### ISSUE THREAD

**Issue by BeniRupp** [docker-library/drupal#272]
There is a vulnerable version of `postgresql` in `drupal:10.3.6-php8.3-fpm-alpine3.20`. ([CVE-2024-7348](https://scout.docker.com/vulnerabilities/id/CVE-2024-7348?s=alpine&n=postgresql16&ns=alpine&t=apk&osn=alpine&osv=3.20&vr=%3C16.4-r0))

`postgresql-dev` is installed in version `16.3-r0`. (`(64/65) Installing postgresql16-dev (16.3-r0)` in [Pipeline](https://github.com/docker-library/drupal/actions/runs/11536035652/job/32111824750)).

There is a newer pipeline run which installed `16.4-r0` (`(64/65) Installing postgresql16-dev (16.4-r0)` in [Pipeline](https://github.com/docker-library/drupal/actions/runs/11646908439/job/32431553119)) that fixes the vulnerability.

What needs to be done to publish this fixed version to docker hub?

**Comment by tianon** [comment]
CVE-2024-7348 is a vulnerability in `pg_dump`, which is not installed in the Drupal images (so this is a false positive). :sweat_smile:

The pipelines you've linked to are our (GitHub repo) local smoke tests - the official builds happen in a much more complex way (especially since they need to support a wider range of architectures than GHA does).  They're primarily (re-)triggered on source updates (changes to our `Dockerfile`s) or base image updates.  Occasionally, those get triggered out-of-band, but usually only for severe issues.

In this case, given that it's technically a false positive _and_ Alpine isn't an officially supported PostgreSQL upstream platform, I don't think it's worth the effort. :bow:

(You might also find https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves interesting/useful.)

**Comment by BeniRupp** [comment]
Thanks, @tianon, for the detailed answer! 👍 I've learned something. 😉
