### ISSUE TITLE
missing php.ini file containing the date.timezone parameter

### ISSUE THREAD

**Issue by juliencarnot** [docker-library/drupal#29]
I've come accross this error when accessing the drupal 8.0.1 container front page as anonymous visitor:

Uncaught PHP Exception Exception: "DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone." at /var/www/html/core/lib/Drupal/Core/EventSubscriber/FinishResponseSubscriber [...]

Looking to the [php image page](https://hub.docker.com/_/php/), adding a php.ini in the dockerfile seems to be recommended. I don't know if this should be in this dockerfile or just documented on the page, since the appropriate timezone might be different for every user...

**Comment by yosifkit** [comment]
I agree that with different timezones, it should probably be documented rather than forced.  We just need to https://github.com/docker-library/docs/blob/master/drupal/content.md

**Comment by tianon** [comment]
Sorry for the delay here -- in reading through the (very long and very old) https://www.drupal.org/project/drupal/issues/325827, I get the impression that the value of `date.timezone` doesn't actually make much functional difference since the web UI will use a user-configured timezone in almost all cases, so it _should_ be reasonably safe for us to set this value directly in the image to UTC (assuming this issue still applies and the warning/error is reproducible).

**Comment by tianon** [comment]
In testing to make sure this is still an issue, during the setup process, it asked me for a "Default timezone", and I cannot manage to get any page to crash while logged out, so I believe this is actually fixed. :+1:
