### ISSUE TITLE
Problem with volumes

### ISSUE THREAD

**Issue by signofkoen** [docker-library/drupal#46]
I'm trying to run a Drupal container but I keep getting this error. https://gyazo.com/a7c50a1d8cf9502a3f667063352a425e

I used the following command to create a container with the necessary volume mounts:
docker run --name drupal -p 80:80 -v /data/drupal/sites:/var/www/html/sites/default/files -v /data/drupal/themes:/var/www/html/themes -v /data/drupal/profiles:/var/www/html/profiles -v /data/drupal/modules:/var/www/html/modules --link redis:redis --link mariadb:mysql -d drupal

I'm doing something wrong or is this a known issue?

**Comment by mstenta** [comment]
Are you selecting a non-English language during installation?

If so, do you have a "translations" directory in sites/default/files?

I haven't worked with Drupal translations myself, but I think it expects that folder to be there if you are doing a non-English install.  I don't think this is a docker-specific issue, although maybe it's due to the fact that you're using a volume for sites/default/files?  Does it work if you create a "translations" folder in your /data/drupal/sites folder on the host?

**Comment by wglambert** [comment]
Looks like the issue was resolved, going to prune.
If you believe this to be in error then let me know and I'll re-open it
