### ISSUE TITLE
Can't mount /var/www/html/ to host

### ISSUE THREAD

**Issue by signofkoen** [docker-library/drupal#66]
I wanted to mount /var/www/html/ to a host folder but when I do so. Drupal seems to not install at all,

Is there some work around this problem?

**Comment by mstenta** [comment]
@signofkoen This is because the Dockerfile itself is downloading and unpacking Drupal core in /var/www/html - but when you mount a folder as a volume, it does not automatically copy existing files (ie: Drupal core) into the volume - so you end up with an empty /var/www/html folder.

I put together a pull request that moves the Drupal download and unpacking process into an entrypoint script, along with some automatic updating, so that /var/www/html can be mounted as a volume.

The PR is here: https://github.com/docker-library/drupal/pull/63

And here is where a lot of the discussion has been: #3 

Please try that out and chime in on #3 if you think it's a good approach. It needs more testing and discussion I think before everyone can agree that it makes sense.

**Comment by remon-georgy** [comment]
I believe what @mstenta suggests is a neat solution. But what I do for now is
1. Mount a volume as you do.
2. Accept that it will override guests /var/www/html.
3. Copy a new Drupal instance into the mount point.

That works perfectly for me as I need to track the entire Drupal installation under git.

**Comment by signofkoen** [comment]
Thanks @remon-georgy & @mstenta
