### ISSUE TITLE
Support for Azure SQL

### ISSUE THREAD

**Issue by anweiss** [docker-library/drupal#75]
Been trying to get Azure SQL working with version 8 of this image but to no avail. Is there a way to include support for the Drupal driver for Azure SQL (https://www.drupal.org/project/sqlsrv)?

**Comment by yosifkit** [comment]
It is not too bad to enable.  I documented the steps a few weeks ago in an issue on the php repo: https://github.com/docker-library/php/issues/372#issuecomment-279051574.  You should be able to throw those commands into a Dockerfile and have an image with `sqlsrv` installed.

I'm not sure we should install it by default in the `drupal` image, since we currently only enable [modules already included](https://github.com/docker-library/drupal/blob/959a9c634708a3d1b45cbc8ac60caaf7952ccac9/8.2/apache/Dockerfile#L7-L10) with php source (ie no `pecl install` yet).

**Comment by anweiss** [comment]
Perfect, thanks! Maybe there should at least be guidance on this in the README?

**Comment by yosifkit** [comment]
Closing old issue.
